version: '3.1'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped    
    container_name: db_flower
    ports: 
      - 5432:5432 
    env_file:
      - database.env    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  # volumes:
  #  - database-data:/var/lib/postgresql/data/