version: '3.1'

services:
  postgres:
    image: postgres:13.2-alpine
    restart: always   
    container_name: flower_db
    volumes:
     # - ./postgres-data:/var/lib/postgresql/data/
      - ./db:/docker-entrypoint-initdb.d/
    ports: 
      - 5438:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=flower

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
     
  